Recurring feature
payout-one/payout_prestashop_old pull request #4
Opened 2021-12-16 03:56 UTC by sumansphinx

Hi Oliver,

recurring payment feature is implemented

Regards,
Suman

2021-12-16 11:22 UTC, oliver-kriska requested changes

2021-12-16 11:22 UTC, oliver-kriska commented on payout/classes/Checkout.php
> +        //if (isset($data['recurrent_token']) && is_array($data['recurrent_token'])) {
```suggestion
```

2021-12-16 11:22 UTC, oliver-kriska commented on payout/controllers/front/confirmation.php
> +                //echo $secure_key = Context::getContext()->customer->secure_key;
```suggestion
```

2021-12-16 11:22 UTC, oliver-kriska commented on payout/controllers/front/webhook.php
> +                    //echo $secure_key = Context::getContext()->customer->secure_key;
```suggestion
```

2021-12-16 11:22 UTC, oliver-kriska commented on payout/controllers/front/webhook.php
> +                        //Tools::redirect('index.php?controller=order&step=1');
Do you need this commented line? if not, please remove

2021-12-16 11:22 UTC, oliver-kriska commented on payout/controllers/front/webhook.php
> +                        //Tools::redirect('index.php?controller=order&step=1');
Do you need this commented line? if not, please remove

2021-12-16 11:22 UTC, oliver-kriska commented on payout/payout.php
> +        Configuration::updateValue('PAYOUT_LIVE_MODE', false);
are you sure about this hardcoded update?

2021-12-16 11:22 UTC, oliver-kriska commented on payout/controllers/front/webhook.php
> +                user_token="' . $user_token . '" where id_external="' . $external_id . '"';
Token can not be stored as plain text. It has to be used some crypto logic how we were talking on the beginning.

2021-12-16 16:38 UTC, sumansphinx commented on payout/payout.php
> +        Configuration::updateValue('PAYOUT_LIVE_MODE', false);
Hi Oliver,

If I use the updateValue function it will update the data if available and if not available it creates a new configuration data, and it is related to the sandbox mode like if the the **PAYOUT_LIVE_MODE** is set to false it will act with sandbox data. 
so yes it is correct not need to change as per me.

Regards,
Suman

2021-12-16 16:39 UTC, sumansphinx commented on payout/controllers/front/webhook.php
> +                user_token="' . $user_token . '" where id_external="' . $external_id . '"';
I have corrected the way and added the openssl encryption method here.

2021-12-16 16:39 UTC, sumansphinx commented
Hi Oliver,


I have updated the PR.


request you to please validate it.


Regards,
Suman

2021-12-16 21:34 UTC, oliver-kriska approved these changes

2021-12-23 05:31 UTC, sumansphinx commented
Hi Oliver,


Request you to please validate the PR where i have added the encryption from file. as discussed.


Regards,
Suman

2021-12-23 08:36 UTC, oliver-kriska requested changes

2021-12-23 08:36 UTC, oliver-kriska commented on payout/controllers/front/validation.php
> +        // die();
please remove comments if you don't need them in future. Thanks

2021-12-23 08:36 UTC, oliver-kriska commented on payout/payout.php
> +        $config = require _PS_CACHE_DIR_ . 'appParameters.php';
`appParameters.php` this file will be created in installation process? I don't see code for creating this file.

2021-12-23 10:57 UTC, sumansphinx commented on payout/payout.php
> +        $config = require _PS_CACHE_DIR_ . 'appParameters.php';
Hi Oliver,

This file is the config file created at the time of the installation. whenever the cache is cleared then it again creates from the details stored in parameters.php


Regards,
Suman

2021-12-23 10:58 UTC, sumansphinx commented on payout/controllers/front/validation.php
> +        // die();
Hi Oliver,

I have removed the comment from the validation file.


Regards,
Suman

2021-12-23 10:59 UTC, oliver-kriska commented on payout/payout.php
> +        $config = require _PS_CACHE_DIR_ . 'appParameters.php';
ok, so everytime when someone clear the cache, key is lost?

2021-12-23 11:23 UTC, sumansphinx commented on payout/payout.php
> +        $config = require _PS_CACHE_DIR_ . 'appParameters.php';
Hi Oliver,


Normally key is stored in the parameter.php and whenever cache is cleared then appparameters.php is regenerated with the same credentials available in the parameter.php. so key will not lost.

Regards,
Suman

2021-12-25 06:25 UTC, oliver-kriska commented on payout/payout.php
> +        $config = require _PS_CACHE_DIR_ . 'appParameters.php';
great

2021-12-25 06:26 UTC, oliver-kriska approved these changes
Hi, please merge it to the master, changelon and prepare zip files for installation.  I will make release. Thanks

2022-01-03 11:22 UTC, merged